[template]
src   = "confd_settings.py"
dest  = "/templates/confd_settings.py"
uid = 1000
gid = 1000
mode  = "0640"
keys = [
  "/deis",
]
check_cmd = "test -e {{ .src }}"
reload_cmd = "/app/bin/reload"
